import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  bottomLinearGradient: {
    height: 2,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    maxHeight: 100,
    marginHorizontal: 16,
  },
  input: {
    flex: 1,
    flexGrow: 1,
    paddingVertical: 4,
    paddingRight: 12,
    marginVertical: 8,
    fontSize: 16,
    flexWrap: 'wrap',
    marginLeft: 8,
  },
  actionButtonContainer: {
    marginHorizontal: 4,
    backgroundColor: 'rgba(229, 229, 229, 0.81)',
    width: 35,
    height: 35,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonPhoto: {
    width: 18,
    height: 15,
    resizeMode: 'contain',
  },
  actionButtonImage: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  btnContainer: {
    marginRight: 12,
  },
  sendBtn: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  recordBtn: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  btnRecord: {
    width: 35,
    height: 35,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  messageContainer: {
    paddingHorizontal: 4,
    marginVertical: 2,
  },
  messageOwnContent: {},
  messageContent: {},
  messageInnerContent: {
    marginHorizontal: 4,
    minHeight: 42,
    minWidth: 50,
    borderTopLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  photoInnerContent: {
    marginHorizontal: 8,
    position: 'relative',
  },
  contentBackground: {
    width: 48,
    height: 36,
    resizeMode: 'contain',
    position: 'absolute',
  },
  contentOtherBackground: {
    transform: [{rotateY: '180deg'}],
    width: 48,
    height: 36,
    resizeMode: 'contain',
    position: 'absolute',
  },
  messageText: {
    fontFamily: 'Raleway',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 22,
  },
  messageTimeText: {
    fontFamily: 'Hind Vadodara',
    fontSize: 12,
    lineHeight: 22,
    alignSelf: 'flex-end',
  },
  imageMsg: {
    width: 200,
    height: 200,
    padding: 4,
    marginRight: 5,
    marginTop: 3,
    borderRadius: 8,
    overflow: 'hidden',
  },
  imageOtherMsg: {
    width: 200,
    height: 200,
    padding: 4,
    marginLeft: 5,
    marginTop: 3,
    borderRadius: 8,
    overflow: 'hidden',
  },
  photoMessage: {
    width: '100%',
    height: '100%',
  },
  noPosts: {
    marginTop: 40,
    alignSelf: 'center',
  },
  dateSeparator: {
    paddingHorizontal: 16,
    borderRadius: 100,
    alignSelf: 'center',
  },
  dateSepText: {
    fontFamily: 'Hind Vadodara',
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 22,
  },
  activeImageContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    backgroundColor: '#000000E0',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
  row: {
    flexDirection: 'row',
  },
  avatarContainer: {
    flexDirection: 'row',
    position: 'relative',
  },
  itemImage: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  badge: {
    bottom: 0,
    right: 0,
    borderWidth: 2,
    position: 'absolute',
  },
  displayName: {
    fontFamily: 'Hind Vadodara',
    fontSize: 16,
    fontWeight: '600',
  },
  status: {
    fontFamily: 'Hind Vadodara',
    fontSize: 12,
    lineHeight: 14,
  },
});
