export const COLOR_WHITE = '#ffffff';
export const COLOR_BLACK = '#2F3131';
export const COLOR_GRAY_DARK = '#858585';
export const COLOR_LIGHT_DARK = '#C4C4C4';
export const COLOR_YELLOW = '#F5BF4D';
export const COLOR_RED = '#E2665E';
export const COLOR_TRANSPARENT = 'transparent';

export const COLOR_BTN_BACKGROUND = '#1D1C1C';
export const COLOR_BTN_TITLE = '#FFFFFF';
export const COLOR_BTN_BORDER = '#585858';

export const themes = {
  light: {
    activeTintColor: '#2F3131',
    backgroundColor: '#FFFFFF',
    focusedBackground: '#F6F5F2',
    borderColor: '#C4C4C4',
    popupBackground: '#FFFFFF',
    postBackground: '#F6F5F2',
    titleColor: '#2F3131',
    textColor: '#585858',
    subTextColor: '#858585',
    tabActivatedColor: '#605E5E',
    tabInActivatedColor: '#C4C4C4',
    iconColor: 'rgba(47, 49, 49, 0.4)',
    buttonBackground: '#ECEBEB',
    messageOwnBackground: '#ECEBEB',
    messageOtherBackground: '#C4C4C4',
    onlineStatusColor: '#32D674',

    websiteLink: '#F5BF4D',
    normalTextColor: '#C4C4C4',
    buttonBackground: '#1D1C1C',
    disableButtonBackground: '#555555',
    deactiveTintColor: '#858585',

    commentCardBox: '#F6F6F6',
    avatarBorder: '#1B1B1B',

    // buttonTextColor: '#FFFFFF',
    // chatComponentBackground: '#f3f4f5',
    tabBorderColor: '#FBF6E7',
    // tabActivatedBorderColor: '#2F3131',
    // auxiliaryBackground: '#efeff4',
    // avatarBackground: '#caced1',
    // bannerBackground: '#f1f2f4',
    // subTitleColor: '#858585',
    // titleText: '#000000',
    // ownMsgText: '#2F3131',
    // otherMsgText: '#ffffff',
    // ownAuxiliaryText: '#e3e2e2',
    // otherAuxiliaryText: '#51555f',
    // bodyText: '#222222',
    // backdropColor: '#000000',
    // dangerColor: '#f5455c',
    // successColor: '#2de0a5',
    // borderColor: '#e1e5e8',
    // controlText: '#54585e',
    // auxiliaryText: '#9ca2a8',
    // inactiveTintColor: '#898989',
    // infoText: '#858585',
    // readText: '#404040',
    // tintColor: '#1d74f5',
    // tintActive: '#549df9',
    // auxiliaryTintColor: '#ffcfb8',
    // actionTintColor: '#0d3a97',
    actionColor: '#efc455',
    // separatorColor: '#888888',
    // navbarBackground: '#1B202D',
    // headerBorder: '#080808',
    // headerBackground: '#1B202D',
    // headerSecondaryBackground: '#080808',
    // headerTintColor: '#ffffff',
    // headerTitleColor: '#2F3131',
    // headerColor: '#858585',
    // headerSecondaryText: '#1d74f5',
    toastBackground: '#414852',
    // videoBackground: '#1f2329',
    // favoriteBackground: '#ffbb00',
    // hideBackground: '#54585e',
    // messageboxBackground: '#ffffff',
    // searchboxBackground: '#E5EEF1',
    // buttonBackground: '#414852',
    // buttonText: '#000000',
    // modalBackground: '#E6E6E7',
    // menuText: '#999999',
    // sidemenuBackColor: '#FFFFFF',
    // sidemenuTintColor: '#526581',
    // itemPressedColor: '#F6F6F6',
    // moreIcon: '#000000',
    // messageList: '#E6EEFA',
    // message: '#B3B9C9',
    // messageHeader: '#ffffff',
    // dateText: '#333333',
    // chatInput: '#ffffff',
    // sendButton: '#000000',
    // chatInputPlaceholder: 'rgba(65, 65, 65, 0.45)',
    // placeholderColor: '#C4C4C4',
    // vipColor: 'rgba(255, 255, 255, 0.6)',
    // popupBackColor: '#FFFFFF',
    // profileBackground: '#ffffff',
    // jobText: '#6C7A9C',
    // profilePostBorder: '#3030308A',
    // profileHandle: '#8E8E8E',
    // profileMore: '#898989',
    // messageButton: '#ffffff',
    //
    // // Chat/Message Theme
    // chatBackground: '#FFFFFF',
    // chatSecondaryColor: '#FBFBFB',
    // chatBadgeBorderColor: '#F3F3F3',
    // chatHeaderBorder: '#F0F0F0',
    // messageOwnBackground: '#FBFBFB',
    // messageOtherBackground: '#C4C4C4',
    //
    // inputLabel: '#4A4A4A',
    optionButtonBackground: '#FFFFFF',
    // languageTextColor: '#C4C4C4',
    // chevronIcon: '#D2C6A8',
    // tabBar_background: '#FFFFFF',
    // activatedBottomTabBarIconColor: '#605E5E',
    // inActivatedBottomTabBarIconColor: '#C4C4C4',
    // activatedIcon: '#1D1C1C',
    // inActivatedIcon: 'rgba(15, 15, 15, 0.4)',
    // profileBorderColor: '#C4C4C4',
  },
  dark: {
    activeTintColor: '#FFFFFF',
    backgroundColor: '#2F3131',
    focusedBackground: '#2B2A2A',
    borderColor: '#555555',
    popupBackground: '#2F3131',
    postBackground: '#1D1C1C',
    titleColor: '#FFFFFF',
    textColor: '#C4C4C4',
    subTextColor: '#858585',
    tabActivatedColor: '#605E5E',
    tabInActivatedColor: '#C4C4C4',
    iconColor: 'rgba(255, 255, 255, 0.5)',
    buttonBackground: '#3C3E3E',
    messageOwnBackground: '#3C3E3E',
    messageOtherBackground: '#555555',
    onlineStatusColor: '#32D674',

    websiteLink: '#F5BF4D',
    normalTextColor: '#C4C4C4',
    disableButtonBackground: '#555555',
    deactiveTintColor: '#858585',

    commentCardBox: '#3C3E3E',
    avatarBorder: '#FBF6E7',

    // buttonColor: '#1D1C1C',
    // buttonTextColor: '#FFFFFF',
    // buttonPressColor: '#1D1C1C',
    // buttonPressTextColor: '#1D1C1C',
    //
    // chatComponentBackground: '#f3f4f5',
    tabBorderColor: '#FBF6E7',
    // tabActivatedBorderColor: '#FFFFFF',
    // auxiliaryBackground: '#efeff4',
    // avatarBackground: '#caced1',
    // bannerBackground: '#f1f2f4',
    // subTitleColor: '#C4C4C4',
    // titleText: '#ffffff',
    // ownMsgText: '#ffffff',
    // otherMsgText: '#ffffff',
    // ownAuxiliaryText: '#e3e2e2',
    // otherAuxiliaryText: '#51555f',
    // bodyText: '#2f343d',
    // backdropColor: '#000000',
    // dangerColor: '#f5455c',
    // successColor: '#2de0a5',
    // borderColor: '#e1e5e8',
    // controlText: '#54585e',
    // auxiliaryText: '#AFAFAF',
    // inactiveTintColor: '#A2A8B8',
    // infoText: '#C4C4C4',
    // readText: '#404040',
    // tintColor: '#1d74f5',
    // tintActive: '#549df9',
    // auxiliaryTintColor: '#ffcfb8',
    // actionTintColor: '#0d3a97',
    actionColor: '#efc455',
    // separatorColor: '#6d6d6d',
    // navbarBackground: '#21242C',
    // headerBorder: '#080808',
    // headerBackground: '#21242C',
    // headerSecondaryBackground: '#080808',
    // headerTintColor: '#ffffff',
    // headerTitleColor: '#ffffff',
    // headerColor: '#858585',
    // headerSecondaryText: '#1d74f5',
    toastBackground: '#414852',
    // videoBackground: '#1f2329',
    // favoriteBackground: '#ffbb00',
    // hideBackground: '#54585e',
    // messageboxBackground: '#ffffff',
    // searchboxBackground: '#2F3034',
    // buttonBackground: '#414852',
    // buttonText: '#000000',
    // modalBackground: '#2F3034',
    // menuText: '#999999',
    // sidemenuBackColor: '#21242C',
    // sidemenuTintColor: '#FFFFFF',
    // itemPressedColor: '#2F3336',
    // moreIcon: '#A2A8B8',
    // messageList: '#131517', // '#292F3F',
    // message: '#888888',
    // messageHeader: '#21242C', // '#1B202D',
    // dateText: '#ffffff',
    // chatInput: '#3D4354',
    // sendButton: '#ffffff',
    // chatInputPlaceholder: 'rgba(255, 255, 255, 0.45)',
    // placeholderColor: '#858585',
    // vipColor: 'rgba(0, 0, 0, 0.6)',
    // popupBackColor: '#202326',
    // profileBackground: '#131517',
    // jobText: '#A2A8B8',
    // profilePostBorder: '#A2A8B861',
    // profileHandle: '#A2A8B8',
    // profileMore: '#A2A8B8',
    // messageButton: '#21242C',
    //
    // // Chat/Message Theme
    // chatBackground: '#2F3131',
    // chatSecondaryColor: '#3C3E3E',
    // chatBadgeBorderColor: '#1D1C1C',
    // chatHeaderBorder: '#4A4A4A',
    //
    // inputLabel: '#ffffff',
    optionButtonBackground: '#ECEBEB',
    // languageTextColor: '#ffffff',
    // chevronIcon: '#D2C6A8',
    // tabBar_background: '#2B2D2E',
    // active_tabBar_icon_color: '#C4C4C4',
    // activatedBottomTabBarIconColor: '#605E5E',
    // inActivatedBottomTabBarIconColor: '#C4C4C4',
    // activatedIcon: '#FFFFFF',
    // inActivatedIcon: '#858585',
    // profileBorderColor: '#2B2D2E',
  },
};
